// ─────────────────────────────────────────────────────────────────────────────
// RELEASED FOR RENUMBERING — the documents engineering has actually signed off.
//
// GENERATED by scripts/gen-release-list.mjs from "Ian_Q-24050972-8-0000-0001-G-A11 - Early Works CDDL_JM_25.8.2026.xlsx",
// sheet CDDL_Ian, column "Action (Ian)" = "Proceed with new number".
// Saved 2026-08-28 04:36 by Ian Steynberg. Do not hand-edit.
//
// ⚠️ NOTHING ELSE IS RELEASED, and the reasons differ:
//   · "Not recommeded - spec" — keeps its K038 number, must NOT be renumbered;
//   · "For discussion"        — unresolved;
//   · BLANK                   — the discipline has not been reviewed at all. Every one of
//                               the 101 instrumentation documents is blank today.
// A blank action is not a "no". It means nobody has looked, which is why these are hidden
// rather than shown as rejected.
//
// Discipline split of this release: E 68 · M 4.
// Re-run the generator when engineering fills in more of the Action column.
// ─────────────────────────────────────────────────────────────────────────────

/** Document numbers engineering has released, exactly as written in the workbook. */
export const RELEASED_DOCNOS: string[] = [
  '6105AK038-0100-ED01-0012',
  '6105AK038-0100-ED01-0013',
  '6105AK038-0100-ED01-0014',
  '6105AK038-0100-ED01-0015',
  '6105AK038-0100-ED01-0016',
  '6105AK038-0100-ED01-0017',
  '6105AK038-0100-ED01-0019',
  '6105AK038-0100-ED01-0020',
  '6105AK038-0100-ED01-0022',
  '6105AK038-0100-ED01-0023',
  '6105AK038-0100-ED01-0024',
  '6105AK038-0100-ED01-0025',
  '6105AK038-0100-ED01-0026',
  '6105AK038-0100-ED01-0027',
  '6105AK038-0100-ED01-0028',
  '6105AK038-0100-ED01-0029',
  '6105AK038-0100-ED01-0030',
  '6105AK038-0100-ED01-0031',
  '6105AK038-0100-ED01-0032',
  '6105AK038-0100-ED01-0033',
  '6105AK038-0100-ED01-0034',
  '6105AK038-0100-ED01-0035',
  '6105AK038-0100-ED01-0036',
  '6105AK038-0100-ED01-0037',
  '6105AK038-0100-ED01-0038',
  '6105AK038-0100-ED01-0039',
  '6105AK038-0100-ED02-0003',
  '6105AK038-0100-ED05-0001',
  '6105AK038-0100-ED05-0003',
  '6105AK038-0100-ED05-0005',
  '6105AK038-0100-ED05-0006',
  '6105AK038-0100-ED05-0007',
  '6105AK038-0100-ED05-0008',
  '6105AK038-0100-ED05-0012',
  '6105AK038-0100-ED05-0013',
  '6105AK038-0100-ED05-0014',
  '6105AK038-0100-ED05-0015',
  '6105AK038-0100-ED05-0016',
  '6105AK038-0100-ED05-0017',
  '6105AK038-0100-ED05-0018',
  '6105AK038-0100-ED05-0019',
  '6105AK038-0100-ED05-0020',
  '6105AK038-0100-ED05-0021',
  '6105AK038-0100-ED05-0022',
  '6105AK038-0100-ED05-0023',
  '6105AK038-0100-ED05-0024',
  '6105AK038-0100-ED05-0025',
  '6105AK038-0100-ED17-0001',
  '6105AK038-0100-ED17-0002',
  '6105AK038-0100-ED17-0003',
  '6105AK038-0100-ED17-0004',
  '6105AK038-0100-ED17-0005',
  '6105AK038-0100-ED17-0006',
  '6105AK038-0100-ED17-0007',
  '6105AK038-0100-ED17-0008',
  '6105AK038-0100-ED17-0009',
  '6105AK038-0100-ED17-0010',
  '6105AK038-0100-ED17-0011',
  '6105AK038-0100-ED17-0012',
  '6105AK038-0100-ED17-0013',
  '6105AK038-0100-ED17-0017',
  '6105AK038-0100-ED17-0018',
  '6105AK038-0100-ED17-0019',
  '6105AK038-0100-ED18-0003',
  '6105AK038-0100-ED18-0006',
  '6105AK038-0100-ED18-0007',
  '6105AK038-0100-ED24-0026',
  '6105AK038-0100-MD01-0006',
  '6105AK038-0100-MD01-0007',
  '6105AK038-0100-MD01-0008',
  '6105AK038-0100-MD05-0001',
  '6105AK038-6171-ED05-0004',
]

export const RELEASE_SOURCE = "Ian_Q-24050972-8-0000-0001-G-A11 - Early Works CDDL_JM_25.8.2026.xlsx"
export const RELEASE_SAVED_AT = "2026-08-28 04:36"
