// AUTO-GENERATED (scratchpad/gen_estimator.py) — do not hand-edit the tables.
// CDDL hour estimator: RDMC Phase-1 resource man-hour model (Vossie) collapsed to
// Discipline x DocType archetypes (avg scenario hours), CALIBRATED so the K124 CDDL
// totals to the 69,116 h engineering scope (factor 0.8067).
// Sync-safe by construction: these are CODE, so the 06:00 cddl_doc DELETE+reinsert
// cannot touch them. Planned hours are DERIVED at read-time from each doc's codes.

export const DISC_NAME: Record<string, string> = {
  "A": "Architectural",
  "B": "Project Controls",
  "C": "Civil/Concrete",
  "D": "Supply Chain",
  "E": "Electrical",
  "F": "Process",
  "G": "General",
  "H": "Health & Safety / Security",
  "I": "Instrumentation",
  "J": "Environmental / Social Impact",
  "L": "Human Resources",
  "M": "Mechanical",
  "N": "Mining",
  "P": "Piping",
  "Q": "Quality & Control / HAZOP / HAZID / Risk",
  "S": "Structural",
  "T": "Geotechnical",
  "U": "Pipeline",
  "W": "Earthworks / Drainage / Fencing / Roads / Water"
}

export const TYPE_NAME: Record<string, string> = {
  "SPC": "Specification",
  "GAD": "General Arrangement",
  "STD": "Standard Drawings",
  "DIA": "Diagram",
  "CAL": "Calculation",
  "TMP": "Templates",
  "DST": "Datasheet",
  "SEC": "Section",
  "LAY": "Layout",
  "PRC": "Procedure",
  "MDL": "Models",
  "QRA": "Quantitive Risk Assessment",
  "PLN": "Plan",
  "SLD": "Single Line Diagram",
  "TRP": "Test Report",
  "RPT": "Report",
  "LST": "List/Matrix",
  "FND": "Foundation",
  "PHL": "Philosophy",
  "PPL": "Plot Plan",
  "SHP": "Shop Drawings",
  "ELE": "Elevation",
  "EQL": "Equipment List",
  "NAR": "Narrative",
  "DTL": "Details",
  "DBD": "Design Basis and Criteria",
  "SSD": "Structural Steel Drawings",
  "DID": "Ducting and Instrument Diagram",
  "PID": "Piping and Instrumentation Diagram",
  "PFD": "Process Flow Diagram",
  "ISO": "Isometrics",
  "MTO": "Material Take Off",
  "ITP": "Inspection Test Plan",
  "SCH": "Schedule",
  "SOW": "Scope of Work",
  "BOM": "Bill of Material",
  "BOS": "Basis of Schedule",
  "BOE": "Basis of Estimate",
  "LTR": "Letter",
  "MOM": "Minutes of Meeting",
  "STR": "Strategy",
  "PCN": "Project Change Notice",
  "IOM": "Installation Operation and Maintenance Manual",
  "MAN": "Manual",
  "REQ": "Request",
  "RFI": "Request for Information",
  "TDN": "Trends",
  "TOR": "Terms of Reference",
  "WLD": "Welding",
  "HAC": "Hazard Classification",
  "NCR": "Non-Conformance Report",
  "SKT": "Sketch",
  "CAE": "Cause and Effect Drawing",
  "TIE": "Tie-In"
}

const ARCH: Record<string, number> = {
  "architectural|standard drawings": 6.33,
  "civil concrete|calculation": 3.55,
  "civil concrete|ducting and instrument diagram": 7.73,
  "civil concrete|foundation drawings": 11.81,
  "civil concrete|general arrangement": 17.1,
  "civil concrete|models": 35.44,
  "civil concrete|piping specialty item list": 2.38,
  "civil concrete|plan (drawing)": 16.82,
  "civil concrete|plot plan": 12.33,
  "civil concrete|section": 18.13,
  "civil concrete|shop drawings": 8.03,
  "civil concrete|specification": 10.72,
  "civil concrete|standard drawings": 22.29,
  "civil concrete|standards": 5.46,
  "civil concrete|structural steel drawings": 7.81,
  "earthworks   drainage   fencing   roads   water|elevation": 4.45,
  "earthworks   drainage   fencing   roads   water|layout": 9.17,
  "earthworks   drainage   fencing   roads   water|test report": 3.74,
  "electrical|calculation": 13.01,
  "electrical|datasheet": 25.12,
  "electrical|design basis and criteria": 18.78,
  "electrical|diagram": 25.31,
  "electrical|equipment list": 12.7,
  "electrical|general arrangement": 17.66,
  "electrical|guideline": 1.6,
  "electrical|layout": 14.17,
  "electrical|models": 14.81,
  "electrical|narrative": 4.27,
  "electrical|procedure": 0.61,
  "electrical|quantitive risk assessment": 14.78,
  "electrical|report": 5.4,
  "electrical|single line diagram": 18.12,
  "electrical|specification": 15.2,
  "electrical|standard drawings": 14.76,
  "electrical|standards": 13.96,
  "electrical|strategy": 3.09,
  "electrical|structural steel drawings": 17.37,
  "general|bill of material": 35.11,
  "general|calculation": 1.98,
  "general|inspection test plan": 10.41,
  "general|list matrix": 11.04,
  "general|master document register": 11.04,
  "general|procedure": 9.65,
  "general|report": 0.69,
  "general|schedule": 62.5,
  "geotechnical|report": 4.74,
  "geotechnical|specification": 9.55,
  "instrumentation|calculation": 8.09,
  "instrumentation|design basis and criteria": 1.59,
  "instrumentation|diagram": 5.09,
  "instrumentation|hazard classification": 8.09,
  "instrumentation|instrumentation drawing": 9.72,
  "instrumentation|list matrix": 4.75,
  "instrumentation|narrative": 11.92,
  "instrumentation|piping and instrumentation diagram": 8.4,
  "instrumentation|process flow diagram": 9.85,
  "instrumentation|quantitive risk assessment": 6.03,
  "instrumentation|specification": 7.29,
  "instrumentation|standard drawings": 4.07,
  "instrumentation|standards": 3.34,
  "mechanical|calculation": 4.58,
  "mechanical|datasheet": 3.99,
  "mechanical|equipment list": 4.91,
  "mechanical|isometrics": 4.89,
  "mechanical|piping support": 3.23,
  "mechanical|procedure": 4.15,
  "mechanical|quality assurance documents": 5.36,
  "mechanical|shop drawings": 1.33,
  "mechanical|specification": 4.69,
  "mechanical|standard drawings": 5.8,
  "process|design basis and criteria": 8.17,
  "process|diagram": 8.54,
  "process|layout": 3.91,
  "process|list matrix": 3.42,
  "process|narrative": 7.14,
  "process|philosophy": 3.54,
  "process|procedure": 3.14,
  "process|specification": 4.92,
  "project controls|design basis and criteria": 5.03,
  "project controls|list matrix": 11.04,
  "project controls|philosophy": 10.03,
  "project controls|report": 18.51,
  "project controls|specification": 6.01,
  "project controls|standard drawings": 5.76,
  "supply chain|material take off": 13.19,
  "supply chain|report": 21.99
}

const ARCH_TYPE: Record<string, number> = {
  "bill of material": 35.11,
  "calculation": 8.89,
  "datasheet": 20.62,
  "design basis and criteria": 6.04,
  "diagram": 17.66,
  "ducting and instrument diagram": 7.73,
  "elevation": 4.45,
  "equipment list": 9.54,
  "foundation drawings": 11.81,
  "general arrangement": 17.17,
  "guideline": 1.6,
  "hazard classification": 8.09,
  "inspection test plan": 10.41,
  "instrumentation drawing": 9.72,
  "isometrics": 4.89,
  "layout": 10.18,
  "list matrix": 4.76,
  "master document register": 11.04,
  "material take off": 13.19,
  "models": 26.65,
  "narrative": 7.26,
  "philosophy": 8.09,
  "piping and instrumentation diagram": 8.4,
  "piping specialty item list": 2.38,
  "piping support": 3.23,
  "plan (drawing)": 16.82,
  "plot plan": 12.33,
  "procedure": 5.01,
  "process flow diagram": 9.85,
  "quality assurance documents": 5.36,
  "quantitive risk assessment": 11.44,
  "report": 13.78,
  "schedule": 62.5,
  "section": 18.13,
  "shop drawings": 5.52,
  "single line diagram": 18.12,
  "specification": 9.33,
  "standard drawings": 14.86,
  "standards": 10.63,
  "strategy": 3.09,
  "structural steel drawings": 8.16,
  "test report": 3.74
}

const ARCH_DISC: Record<string, number> = {
  "architectural": 6.33,
  "civil concrete": 15.0,
  "earthworks   drainage   fencing   roads   water": 5.64,
  "electrical": 16.5,
  "general": 10.44,
  "geotechnical": 7.39,
  "instrumentation": 6.52,
  "mechanical": 4.36,
  "process": 6.24,
  "project controls": 11.2,
  "supply chain": 19.64
}

const GLOBAL = 12.08

const norm = (s: string) => s.trim().toLowerCase().replace(/[/-]/g, ' ').replace(/\s+/g, ' ')

/** Estimated planned hours for a CDDL document from its discipline + doc-type CODES.
 *  Falls back doc-type-only -> discipline-only -> global. Returns hours (calibrated). */
export function estimateHours(discCode?: string | null, typeCode?: string | null): number {
  const dn = norm(DISC_NAME[(discCode ?? "").trim()] ?? "")
  const tn = norm(TYPE_NAME[(typeCode ?? "").trim()] ?? "")
  if (dn && tn && ARCH[`${dn}|${tn}`] != null) return ARCH[`${dn}|${tn}`]
  if (tn && ARCH_TYPE[tn] != null) return ARCH_TYPE[tn]
  if (dn && ARCH_DISC[dn] != null) return ARCH_DISC[dn]
  return GLOBAL
}
