// AUTO-GENERATED (scratchpad/gen_estimator.py) — do not hand-edit the tables.
// CDDL hour estimator: RDMC Phase-1 resource man-hour model (Vossie) collapsed to
// Discipline x DocType archetypes (avg scenario hours), CALIBRATED so the K124 CDDL
// totals to the direct-engineering hours ~43,386 h (70% of the 61,980 h CoreTime
// X146 engineering budget; BoS split 70 eng / 20 review / 10 meetings). Flat factor 0.5064.
// Sync-safe by construction: these are CODE, so the 06:00 cddl_doc DELETE+reinsert
// cannot touch them. Planned hours are DERIVED at read-time from each doc's codes.

export const DISC_NAME: Record<string, string> = {
  "A": "Architectural",
  "B": "Project Controls",
  "C": "Civil/Concrete",
  "D": "Supply Chain",
  "E": "Electrical",
  "F": "Process",
  "G": "General",
  "H": "Health & Safety / Security",
  "I": "Instrumentation",
  "J": "Environmental / Social Impact",
  "L": "Human Resources",
  "M": "Mechanical",
  "N": "Mining",
  "P": "Piping",
  "Q": "Quality & Control / HAZOP / HAZID / Risk",
  "S": "Structural",
  "T": "Geotechnical",
  "U": "Pipeline",
  "W": "Earthworks / Drainage / Fencing / Roads / Water"
}

export const TYPE_NAME: Record<string, string> = {
  "SPC": "Specification",
  "GAD": "General Arrangement",
  "STD": "Standard Drawings",
  "DIA": "Diagram",
  "CAL": "Calculation",
  "TMP": "Templates",
  "DST": "Datasheet",
  "SEC": "Section",
  "LAY": "Layout",
  "PRC": "Procedure",
  "MDL": "Models",
  "QRA": "Quantitive Risk Assessment",
  "PLN": "Plan",
  "SLD": "Single Line Diagram",
  "TRP": "Test Report",
  "RPT": "Report",
  "LST": "List/Matrix",
  "FND": "Foundation",
  "PHL": "Philosophy",
  "PPL": "Plot Plan",
  "SHP": "Shop Drawings",
  "ELE": "Elevation",
  "EQL": "Equipment List",
  "NAR": "Narrative",
  "DTL": "Details",
  "DBD": "Design Basis and Criteria",
  "SSD": "Structural Steel Drawings",
  "DID": "Ducting and Instrument Diagram",
  "PID": "Piping and Instrumentation Diagram",
  "PFD": "Process Flow Diagram",
  "ISO": "Isometrics",
  "MTO": "Material Take Off",
  "ITP": "Inspection Test Plan",
  "SCH": "Schedule",
  "SOW": "Scope of Work",
  "BOM": "Bill of Material",
  "BOS": "Basis of Schedule",
  "BOE": "Basis of Estimate",
  "LTR": "Letter",
  "MOM": "Minutes of Meeting",
  "STR": "Strategy",
  "PCN": "Project Change Notice",
  "IOM": "Installation Operation and Maintenance Manual",
  "MAN": "Manual",
  "REQ": "Request",
  "RFI": "Request for Information",
  "TDN": "Trends",
  "TOR": "Terms of Reference",
  "WLD": "Welding",
  "HAC": "Hazard Classification",
  "NCR": "Non-Conformance Report",
  "SKT": "Sketch",
  "CAE": "Cause and Effect Drawing",
  "TIE": "Tie-In"
}

const ARCH: Record<string, number> = {
  "architectural|standard drawings": 3.98,
  "civil concrete|calculation": 2.23,
  "civil concrete|ducting and instrument diagram": 4.85,
  "civil concrete|foundation drawings": 7.41,
  "civil concrete|general arrangement": 10.73,
  "civil concrete|models": 22.24,
  "civil concrete|piping specialty item list": 1.49,
  "civil concrete|plan (drawing)": 10.56,
  "civil concrete|plot plan": 7.74,
  "civil concrete|section": 11.38,
  "civil concrete|shop drawings": 5.04,
  "civil concrete|specification": 6.73,
  "civil concrete|standard drawings": 13.99,
  "civil concrete|standards": 3.43,
  "civil concrete|structural steel drawings": 4.9,
  "earthworks   drainage   fencing   roads   water|elevation": 2.8,
  "earthworks   drainage   fencing   roads   water|layout": 5.75,
  "earthworks   drainage   fencing   roads   water|test report": 2.35,
  "electrical|calculation": 8.17,
  "electrical|datasheet": 15.77,
  "electrical|design basis and criteria": 11.79,
  "electrical|diagram": 15.89,
  "electrical|equipment list": 7.97,
  "electrical|general arrangement": 11.09,
  "electrical|guideline": 1.01,
  "electrical|layout": 8.89,
  "electrical|models": 9.29,
  "electrical|narrative": 2.68,
  "electrical|procedure": 0.38,
  "electrical|quantitive risk assessment": 9.28,
  "electrical|report": 3.39,
  "electrical|single line diagram": 11.38,
  "electrical|specification": 9.54,
  "electrical|standard drawings": 9.27,
  "electrical|standards": 8.76,
  "electrical|strategy": 1.94,
  "electrical|structural steel drawings": 10.9,
  "general|bill of material": 22.04,
  "general|calculation": 1.25,
  "general|inspection test plan": 6.53,
  "general|list matrix": 6.93,
  "general|master document register": 6.93,
  "general|procedure": 6.06,
  "general|report": 0.43,
  "general|schedule": 39.23,
  "geotechnical|report": 2.98,
  "geotechnical|specification": 5.99,
  "instrumentation|calculation": 5.08,
  "instrumentation|design basis and criteria": 1.0,
  "instrumentation|diagram": 3.19,
  "instrumentation|hazard classification": 5.08,
  "instrumentation|instrumentation drawing": 6.1,
  "instrumentation|list matrix": 2.98,
  "instrumentation|narrative": 7.48,
  "instrumentation|piping and instrumentation diagram": 5.27,
  "instrumentation|process flow diagram": 6.18,
  "instrumentation|quantitive risk assessment": 3.79,
  "instrumentation|specification": 4.58,
  "instrumentation|standard drawings": 2.55,
  "instrumentation|standards": 2.1,
  "mechanical|calculation": 2.87,
  "mechanical|datasheet": 2.5,
  "mechanical|equipment list": 3.08,
  "mechanical|isometrics": 3.07,
  "mechanical|piping support": 2.03,
  "mechanical|procedure": 2.61,
  "mechanical|quality assurance documents": 3.36,
  "mechanical|shop drawings": 0.84,
  "mechanical|specification": 2.94,
  "mechanical|standard drawings": 3.64,
  "process|design basis and criteria": 5.13,
  "process|diagram": 5.36,
  "process|layout": 2.46,
  "process|list matrix": 2.15,
  "process|narrative": 4.48,
  "process|philosophy": 2.22,
  "process|procedure": 1.97,
  "process|specification": 3.09,
  "project controls|design basis and criteria": 3.16,
  "project controls|list matrix": 6.93,
  "project controls|philosophy": 6.29,
  "project controls|report": 11.62,
  "project controls|specification": 3.78,
  "project controls|standard drawings": 3.62,
  "supply chain|material take off": 8.28,
  "supply chain|report": 13.8
}

const ARCH_TYPE: Record<string, number> = {
  "bill of material": 22.04,
  "calculation": 5.58,
  "datasheet": 12.94,
  "design basis and criteria": 3.79,
  "diagram": 11.09,
  "ducting and instrument diagram": 4.85,
  "elevation": 2.8,
  "equipment list": 5.99,
  "foundation drawings": 7.41,
  "general arrangement": 10.78,
  "guideline": 1.01,
  "hazard classification": 5.08,
  "inspection test plan": 6.53,
  "instrumentation drawing": 6.1,
  "isometrics": 3.07,
  "layout": 6.39,
  "list matrix": 2.99,
  "master document register": 6.93,
  "material take off": 8.28,
  "models": 16.73,
  "narrative": 4.55,
  "philosophy": 5.08,
  "piping and instrumentation diagram": 5.27,
  "piping specialty item list": 1.49,
  "piping support": 2.03,
  "plan (drawing)": 10.56,
  "plot plan": 7.74,
  "procedure": 3.14,
  "process flow diagram": 6.18,
  "quality assurance documents": 3.36,
  "quantitive risk assessment": 7.18,
  "report": 8.65,
  "schedule": 39.23,
  "section": 11.38,
  "shop drawings": 3.46,
  "single line diagram": 11.38,
  "specification": 5.86,
  "standard drawings": 9.33,
  "standards": 6.67,
  "strategy": 1.94,
  "structural steel drawings": 5.12,
  "test report": 2.35
}

const ARCH_DISC: Record<string, number> = {
  "architectural": 3.98,
  "civil concrete": 9.42,
  "earthworks   drainage   fencing   roads   water": 3.54,
  "electrical": 10.36,
  "general": 6.55,
  "geotechnical": 4.64,
  "instrumentation": 4.1,
  "mechanical": 2.74,
  "process": 3.92,
  "project controls": 7.03,
  "supply chain": 12.33
}

const GLOBAL = 7.58

const norm = (s: string) => s.trim().toLowerCase().replace(/[/-]/g, ' ').replace(/\s+/g, ' ')

/** Estimated planned hours for a CDDL document from its discipline + doc-type CODES.
 *  Falls back doc-type-only -> discipline-only -> global. Returns hours (calibrated). */
export function estimateHours(discCode?: string | null, typeCode?: string | null): number {
  const dn = norm(DISC_NAME[(discCode ?? "").trim()] ?? "")
  const tn = norm(TYPE_NAME[(typeCode ?? "").trim()] ?? "")
  if (dn && tn && ARCH[`${dn}|${tn}`] != null) return ARCH[`${dn}|${tn}`]
  if (tn && ARCH_TYPE[tn] != null) return ARCH_TYPE[tn]
  if (dn && ARCH_DISC[dn] != null) return ARCH_DISC[dn]
  return GLOBAL
}
