// AUTO-GENERATED (scratchpad/gen_estimator.py) — do not hand-edit the tables.
// CDDL hour estimator: RDMC Phase-1 resource man-hour model (Vossie) collapsed to
// Discipline x DocType archetypes (avg scenario hours), CALIBRATED so the K124 CDDL
// totals to the budget-derived design/create hours ~51,124 h (82.5% of the
// CoreTime X146 engineering budget), a flat reduction of Vossie s ~69k model. Factor 0.5967.
// Sync-safe by construction: these are CODE, so the 06:00 cddl_doc DELETE+reinsert
// cannot touch them. Planned hours are DERIVED at read-time from each doc's codes.

export const DISC_NAME: Record<string, string> = {
  "A": "Architectural",
  "B": "Project Controls",
  "C": "Civil/Concrete",
  "D": "Supply Chain",
  "E": "Electrical",
  "F": "Process",
  "G": "General",
  "H": "Health & Safety / Security",
  "I": "Instrumentation",
  "J": "Environmental / Social Impact",
  "L": "Human Resources",
  "M": "Mechanical",
  "N": "Mining",
  "P": "Piping",
  "Q": "Quality & Control / HAZOP / HAZID / Risk",
  "S": "Structural",
  "T": "Geotechnical",
  "U": "Pipeline",
  "W": "Earthworks / Drainage / Fencing / Roads / Water"
}

export const TYPE_NAME: Record<string, string> = {
  "SPC": "Specification",
  "GAD": "General Arrangement",
  "STD": "Standard Drawings",
  "DIA": "Diagram",
  "CAL": "Calculation",
  "TMP": "Templates",
  "DST": "Datasheet",
  "SEC": "Section",
  "LAY": "Layout",
  "PRC": "Procedure",
  "MDL": "Models",
  "QRA": "Quantitive Risk Assessment",
  "PLN": "Plan",
  "SLD": "Single Line Diagram",
  "TRP": "Test Report",
  "RPT": "Report",
  "LST": "List/Matrix",
  "FND": "Foundation",
  "PHL": "Philosophy",
  "PPL": "Plot Plan",
  "SHP": "Shop Drawings",
  "ELE": "Elevation",
  "EQL": "Equipment List",
  "NAR": "Narrative",
  "DTL": "Details",
  "DBD": "Design Basis and Criteria",
  "SSD": "Structural Steel Drawings",
  "DID": "Ducting and Instrument Diagram",
  "PID": "Piping and Instrumentation Diagram",
  "PFD": "Process Flow Diagram",
  "ISO": "Isometrics",
  "MTO": "Material Take Off",
  "ITP": "Inspection Test Plan",
  "SCH": "Schedule",
  "SOW": "Scope of Work",
  "BOM": "Bill of Material",
  "BOS": "Basis of Schedule",
  "BOE": "Basis of Estimate",
  "LTR": "Letter",
  "MOM": "Minutes of Meeting",
  "STR": "Strategy",
  "PCN": "Project Change Notice",
  "IOM": "Installation Operation and Maintenance Manual",
  "MAN": "Manual",
  "REQ": "Request",
  "RFI": "Request for Information",
  "TDN": "Trends",
  "TOR": "Terms of Reference",
  "WLD": "Welding",
  "HAC": "Hazard Classification",
  "NCR": "Non-Conformance Report",
  "SKT": "Sketch",
  "CAE": "Cause and Effect Drawing",
  "TIE": "Tie-In"
}

const ARCH: Record<string, number> = {
  "architectural|standard drawings": 4.68,
  "civil concrete|calculation": 2.63,
  "civil concrete|ducting and instrument diagram": 5.72,
  "civil concrete|foundation drawings": 8.73,
  "civil concrete|general arrangement": 12.65,
  "civil concrete|models": 26.21,
  "civil concrete|piping specialty item list": 1.76,
  "civil concrete|plan (drawing)": 12.44,
  "civil concrete|plot plan": 9.12,
  "civil concrete|section": 13.41,
  "civil concrete|shop drawings": 5.94,
  "civil concrete|specification": 7.93,
  "civil concrete|standard drawings": 16.49,
  "civil concrete|standards": 4.04,
  "civil concrete|structural steel drawings": 5.77,
  "earthworks   drainage   fencing   roads   water|elevation": 3.3,
  "earthworks   drainage   fencing   roads   water|layout": 6.78,
  "earthworks   drainage   fencing   roads   water|test report": 2.77,
  "electrical|calculation": 9.62,
  "electrical|datasheet": 18.58,
  "electrical|design basis and criteria": 13.89,
  "electrical|diagram": 18.72,
  "electrical|equipment list": 9.39,
  "electrical|general arrangement": 13.06,
  "electrical|guideline": 1.19,
  "electrical|layout": 10.48,
  "electrical|models": 10.95,
  "electrical|narrative": 3.16,
  "electrical|procedure": 0.45,
  "electrical|quantitive risk assessment": 10.93,
  "electrical|report": 3.99,
  "electrical|single line diagram": 13.41,
  "electrical|specification": 11.24,
  "electrical|standard drawings": 10.92,
  "electrical|standards": 10.32,
  "electrical|strategy": 2.28,
  "electrical|structural steel drawings": 12.85,
  "general|bill of material": 25.97,
  "general|calculation": 1.47,
  "general|inspection test plan": 7.7,
  "general|list matrix": 8.16,
  "general|master document register": 8.16,
  "general|procedure": 7.14,
  "general|report": 0.51,
  "general|schedule": 46.23,
  "geotechnical|report": 3.51,
  "geotechnical|specification": 7.06,
  "instrumentation|calculation": 5.98,
  "instrumentation|design basis and criteria": 1.17,
  "instrumentation|diagram": 3.76,
  "instrumentation|hazard classification": 5.98,
  "instrumentation|instrumentation drawing": 7.19,
  "instrumentation|list matrix": 3.52,
  "instrumentation|narrative": 8.81,
  "instrumentation|piping and instrumentation diagram": 6.21,
  "instrumentation|process flow diagram": 7.29,
  "instrumentation|quantitive risk assessment": 4.46,
  "instrumentation|specification": 5.39,
  "instrumentation|standard drawings": 3.01,
  "instrumentation|standards": 2.47,
  "mechanical|calculation": 3.39,
  "mechanical|datasheet": 2.95,
  "mechanical|equipment list": 3.63,
  "mechanical|isometrics": 3.62,
  "mechanical|piping support": 2.39,
  "mechanical|procedure": 3.07,
  "mechanical|quality assurance documents": 3.97,
  "mechanical|shop drawings": 0.98,
  "mechanical|specification": 3.47,
  "mechanical|standard drawings": 4.29,
  "process|design basis and criteria": 6.05,
  "process|diagram": 6.32,
  "process|layout": 2.89,
  "process|list matrix": 2.53,
  "process|narrative": 5.28,
  "process|philosophy": 2.62,
  "process|procedure": 2.32,
  "process|specification": 3.64,
  "project controls|design basis and criteria": 3.72,
  "project controls|list matrix": 8.16,
  "project controls|philosophy": 7.42,
  "project controls|report": 13.69,
  "project controls|specification": 4.45,
  "project controls|standard drawings": 4.26,
  "supply chain|material take off": 9.76,
  "supply chain|report": 16.27
}

const ARCH_TYPE: Record<string, number> = {
  "bill of material": 25.97,
  "calculation": 6.57,
  "datasheet": 15.25,
  "design basis and criteria": 4.47,
  "diagram": 13.06,
  "ducting and instrument diagram": 5.72,
  "elevation": 3.3,
  "equipment list": 7.06,
  "foundation drawings": 8.73,
  "general arrangement": 12.7,
  "guideline": 1.19,
  "hazard classification": 5.98,
  "inspection test plan": 7.7,
  "instrumentation drawing": 7.19,
  "isometrics": 3.62,
  "layout": 7.53,
  "list matrix": 3.52,
  "master document register": 8.16,
  "material take off": 9.76,
  "models": 19.71,
  "narrative": 5.37,
  "philosophy": 5.98,
  "piping and instrumentation diagram": 6.21,
  "piping specialty item list": 1.76,
  "piping support": 2.39,
  "plan (drawing)": 12.44,
  "plot plan": 9.12,
  "procedure": 3.7,
  "process flow diagram": 7.29,
  "quality assurance documents": 3.97,
  "quantitive risk assessment": 8.46,
  "report": 10.2,
  "schedule": 46.23,
  "section": 13.41,
  "shop drawings": 4.08,
  "single line diagram": 13.41,
  "specification": 6.9,
  "standard drawings": 10.99,
  "standards": 7.86,
  "strategy": 2.28,
  "structural steel drawings": 6.04,
  "test report": 2.77
}

const ARCH_DISC: Record<string, number> = {
  "architectural": 4.68,
  "civil concrete": 11.1,
  "earthworks   drainage   fencing   roads   water": 4.18,
  "electrical": 12.21,
  "general": 7.72,
  "geotechnical": 5.47,
  "instrumentation": 4.83,
  "mechanical": 3.22,
  "process": 4.62,
  "project controls": 8.28,
  "supply chain": 14.53
}

const GLOBAL = 8.94

const norm = (s: string) => s.trim().toLowerCase().replace(/[/-]/g, ' ').replace(/\s+/g, ' ')

/** Estimated planned hours for a CDDL document from its discipline + doc-type CODES.
 *  Falls back doc-type-only -> discipline-only -> global. Returns hours (calibrated). */
export function estimateHours(discCode?: string | null, typeCode?: string | null): number {
  const dn = norm(DISC_NAME[(discCode ?? "").trim()] ?? "")
  const tn = norm(TYPE_NAME[(typeCode ?? "").trim()] ?? "")
  if (dn && tn && ARCH[`${dn}|${tn}`] != null) return ARCH[`${dn}|${tn}`]
  if (tn && ARCH_TYPE[tn] != null) return ARCH_TYPE[tn]
  if (dn && ARCH_DISC[dn] != null) return ARCH_DISC[dn]
  return GLOBAL
}
