-- 013 seed: document-request dropdowns (doc types, disciplines, WBS areas) from the workbook.
insert into doc_lookup (kind, code, name, description, meta, sort) values
  ('document_type','AUT','Authority',null,null,0),
  ('document_type','BLT','Battery Limit',null,null,1),
  ('document_type','BOE','Basis of Estimate',null,null,2),
  ('document_type','BOS','Basis of Schedule',null,null,3),
  ('document_type','BOM','Bill of Material',null,null,4),
  ('document_type','CAL','Calculation',null,null,5),
  ('document_type','CHR','Chart',null,null,6),
  ('document_type','CON','Contract',null,null,7),
  ('document_type','DBD','Design Basis and Criteria',null,null,8),
  ('document_type','DBK','Project Data Book',null,null,9),
  ('document_type','DDR','Document and Data Register',null,null,10),
  ('document_type','DEM','Demolition',null,null,11),
  ('document_type','DST','Datasheet',null,null,12),
  ('document_type','DTA','Data (Digital Record)',null,null,13),
  ('document_type','EQL','Equipment List',null,null,14),
  ('document_type','EST','Estimates',null,null,15),
  ('document_type','EXE','Execution',null,null,16),
  ('document_type','FRM','Forms',null,null,17),
  ('document_type','GDL','Guideline',null,null,18),
  ('document_type','HAC','Hazard Classification',null,null,19),
  ('document_type','HMB','Heat Material Balance',null,null,20),
  ('document_type','IDX','Index',null,null,21),
  ('document_type','INS','Instructions',null,null,22),
  ('document_type','IOM','Installation Operation and Maintenance Manual',null,null,23),
  ('document_type','ITP','Inspection Test Plan',null,null,24),
  ('document_type','IWP','Installation Work Package',null,null,25),
  ('document_type','LST','List/Matrix',null,null,26),
  ('document_type','LTR','Letter',null,null,27),
  ('document_type','MAN','Manual',null,null,28),
  ('document_type','MDL','Models',null,null,29),
  ('document_type','MDR','Master Document Register',null,null,30),
  ('document_type','MEM','Memorandum',null,null,31),
  ('document_type','MOM','Minutes of Meeting',null,null,32),
  ('document_type','MTO','Material Take Off',null,null,33),
  ('document_type','NAR','Narrative',null,null,34),
  ('document_type','NCR','Non-Conformance Report',null,null,35),
  ('document_type','PCN','Project Change Notice',null,null,36),
  ('document_type','PDR','Procedure Deviation Request',null,null,37),
  ('document_type','PHL','Philosophy',null,null,38),
  ('document_type','PLN','Plan',null,null,39),
  ('document_type','PLC','Policy',null,null,40),
  ('document_type','PRC','Procedure',null,null,41),
  ('document_type','PRO','Procurement',null,null,42),
  ('document_type','QAD','Quality Assurance Documents',null,null,43),
  ('document_type','QRA','Quantitive Risk Assessment',null,null,44),
  ('document_type','REQ','Request',null,null,45),
  ('document_type','RFA','Recommendation for Award',null,null,46),
  ('document_type','RFI','Request for Information',null,null,47),
  ('document_type','RPT','Report',null,null,48),
  ('document_type','SCH','Schedule',null,null,49),
  ('document_type','SMP','Sample',null,null,50),
  ('document_type','SOP','Standard Operating Procedure',null,null,51),
  ('document_type','SOW','Scope of Work',null,null,52),
  ('document_type','SPC','Specification',null,null,53),
  ('document_type','SPL','Piping Specialty Item List',null,null,54),
  ('document_type','STD','Standards',null,null,55),
  ('document_type','STR','Strategy',null,null,56),
  ('document_type','SUM','Summary',null,null,57),
  ('document_type','TDM','Technical Decision Memorandum',null,null,58),
  ('document_type','TDN','Trends',null,null,59),
  ('document_type','TMP','Templates',null,null,60),
  ('document_type','TOR','Terms of Reference',null,null,61),
  ('document_type','TRP','Test Report',null,null,62),
  ('document_type','TVR','Turnover Dossier',null,null,63),
  ('document_type','VIS','Visualisation',null,null,64),
  ('document_type','WLD','Welding',null,null,65),
  ('document_type','BLT','Battery Limit',null,null,66),
  ('document_type','CAE','Cause and Effect Drawing',null,null,67),
  ('document_type','CRV','Curves',null,null,68),
  ('document_type','DEM','Demolition',null,null,69),
  ('document_type','DIA','Diagram',null,null,70),
  ('document_type','DID','Ducting and Instrument Diagram',null,null,71),
  ('document_type','DTL','Details',null,null,72),
  ('document_type','EHT','Electrical Heat Tracing Isometric',null,null,73),
  ('document_type','ELE','Elevation',null,null,74),
  ('document_type','FND','Foundation Drawings',null,null,75),
  ('document_type','GAD','General Arrangement',null,null,76),
  ('document_type','ITD','Instrumentation Drawing',null,null,77),
  ('document_type','ISO','Isometrics',null,null,78),
  ('document_type','LAY','Layout',null,null,79),
  ('document_type','MSD','Material Selection Diagram',null,null,80),
  ('document_type','PFD','Process Flow Diagram',null,null,81),
  ('document_type','PID','Piping and Instrumentation Diagram',null,null,82),
  ('document_type','PLN','Plan',null,null,83),
  ('document_type','PPL','Plot Plan',null,null,84),
  ('document_type','PSP','Piping Support',null,null,85),
  ('document_type','SEC','Section',null,null,86),
  ('document_type','SHP','Shop Drawings',null,null,87),
  ('document_type','SKT','Sketch',null,null,88),
  ('document_type','SLD','Single Line Diagram',null,null,89),
  ('document_type','SSD','Structural Steel Drawings',null,null,90),
  ('document_type','STD','Standard Drawings',null,null,91),
  ('document_type','TIE','Tie-In',null,null,92),
  ('discipline','A','Architectural',null,null,0),
  ('discipline','B','Project Controls',null,null,1),
  ('discipline','C','Civil/Concrete',null,null,2),
  ('discipline','D','Supply Chain',null,null,3),
  ('discipline','E','Electrical',null,null,4),
  ('discipline','F','Process',null,null,5),
  ('discipline','G','General',null,null,6),
  ('discipline','H','Health & Safety / Security',null,null,7),
  ('discipline','I','Instrumentation',null,null,8),
  ('discipline','J','Environmental / Social Impact',null,null,9),
  ('discipline','L','Human Resources',null,null,10),
  ('discipline','M','Mechanical',null,null,11),
  ('discipline','N','Mining',null,null,12),
  ('discipline','P','Piping',null,null,13),
  ('discipline','Q','Quality & Control / HAZOP / HAZID / Risk',null,null,14),
  ('discipline','S','Structural',null,null,15),
  ('discipline','T','Geotechnical',null,null,16),
  ('discipline','U','Pipeline',null,null,17),
  ('discipline','W','Earthworks / Drainage / Fencing / Roads / Water',null,null,18),
  ('wbs_area','0000','General',null,'{"l1": "0", "l2": "0", "l3": "0", "l4": "0"}'::jsonb,0),
  ('wbs_area','0100','Project Site Wide',null,'{"l1": "0", "l2": "1", "l3": "0", "l4": "0"}'::jsonb,1),
  ('wbs_area','5350','Process Water Dams',null,'{"l1": "5", "l2": "3", "l3": "5", "l4": "0"}'::jsonb,2),
  ('wbs_area','5360','Raw Water Dams',null,'{"l1": "5", "l2": "3", "l3": "6", "l4": "0"}'::jsonb,3),
  ('wbs_area','5370','Turkey Nests',null,'{"l1": "5", "l2": "3", "l3": "7", "l4": "0"}'::jsonb,4),
  ('wbs_area','5530','Village Sewage',null,'{"l1": "5", "l2": "5", "l3": "3", "l4": "0"}'::jsonb,5),
  ('wbs_area','5630','Potable Water Treatment',null,'{"l1": "5", "l2": "6", "l3": "3", "l4": "0"}'::jsonb,6),
  ('wbs_area','6180','Village',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "0"}'::jsonb,7),
  ('wbs_area','6181','Accommodation',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "1"}'::jsonb,8),
  ('wbs_area','6182','Mess Hall and Food Storage',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "2"}'::jsonb,9),
  ('wbs_area','6183','Leisure Amenities',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "3"}'::jsonb,10),
  ('wbs_area','6184','Laundry Facilities',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "4"}'::jsonb,11),
  ('wbs_area','6185','Potable Water and Water Treatment',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "5"}'::jsonb,12),
  ('wbs_area','6186','Firewater - Tank & Fire Fighting System',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "6"}'::jsonb,13),
  ('wbs_area','6187','Support Facilities - Diesel Generators',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "7"}'::jsonb,14),
  ('wbs_area','6188','Underground Services - Sewage Treatment',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "8"}'::jsonb,15),
  ('wbs_area','6189','Common Facilities and Services',null,'{"l1": "6", "l2": "1", "l3": "8", "l4": "9"}'::jsonb,16),
  ('wbs_area','6200','On-Site Power Supply and Transmission',null,'{"l1": "6", "l2": "2", "l3": "0", "l4": "0"}'::jsonb,17),
  ('wbs_area','6210','Power Stations',null,'{"l1": "6", "l2": "2", "l3": "1", "l4": "0"}'::jsonb,18),
  ('wbs_area','6212','Power Station 1',null,'{"l1": "6", "l2": "2", "l3": "1", "l4": "2"}'::jsonb,19),
  ('wbs_area','6230','High Voltage (220 kV) Transmission Lines',null,'{"l1": "6", "l2": "2", "l3": "3", "l4": "0"}'::jsonb,20),
  ('wbs_area','6240','High Voltage Substations',null,'{"l1": "6", "l2": "2", "l3": "4", "l4": "0"}'::jsonb,21),
  ('wbs_area','6241','33/220 kV Solar PV Substation',null,'{"l1": "6", "l2": "2", "l3": "4", "l4": "1"}'::jsonb,22),
  ('wbs_area','6242','33/220 kV Power Station Substation',null,'{"l1": "6", "l2": "2", "l3": "4", "l4": "2"}'::jsonb,23),
  ('wbs_area','6243','220/33 kV Plant Main Substation',null,'{"l1": "6", "l2": "2", "l3": "4", "l4": "3"}'::jsonb,24),
  ('wbs_area','6250','Power Conditioning Equipment',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "0"}'::jsonb,25),
  ('wbs_area','6251','Load Bank',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "1"}'::jsonb,26),
  ('wbs_area','6252','Harmonic Filters 1',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "2"}'::jsonb,27),
  ('wbs_area','6253','Synchronous Condenser 1',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "3"}'::jsonb,28),
  ('wbs_area','6254','Battery Energy Storage System 1',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "4"}'::jsonb,29),
  ('wbs_area','6255','Harmonic Filters 2',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "5"}'::jsonb,30),
  ('wbs_area','6256','Synchronous Condenser 2',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "6"}'::jsonb,31),
  ('wbs_area','6257','Battery Energy Storage System 2',null,'{"l1": "6", "l2": "2", "l3": "5", "l4": "7"}'::jsonb,32),
  ('wbs_area','6260','Emergency Power Generation (Main Plant)',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "0"}'::jsonb,33),
  ('wbs_area','6261','Administration and General Buildings',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "1"}'::jsonb,34),
  ('wbs_area','6262','Emergency Power Substation 1 and Control Room 1',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "2"}'::jsonb,35),
  ('wbs_area','6263','36 MVA Power Station 1',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "3"}'::jsonb,36),
  ('wbs_area','6264','Bulk Diesel Storage 1',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "4"}'::jsonb,37),
  ('wbs_area','6265','Truck Diesel Unloading and Power Station 1',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "5"}'::jsonb,38),
  ('wbs_area','6266','Emergency Power Substation 2 and Control Room 2',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "6"}'::jsonb,39),
  ('wbs_area','6267','36 MVA Power Station 2',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "7"}'::jsonb,40),
  ('wbs_area','6268','Bulk Diesel Storage 2',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "8"}'::jsonb,41),
  ('wbs_area','6269','Truck Diesel Unloading and Power Station 2',null,'{"l1": "6", "l2": "2", "l3": "6", "l4": "9"}'::jsonb,42),
  ('wbs_area','6280','Medium Voltage (33 kV) Overhead Powerlines',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "0"}'::jsonb,43),
  ('wbs_area','6281','Booster Pump Station and Borefields',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "1"}'::jsonb,44),
  ('wbs_area','6282','Potable Water Treatment Plant',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "2"}'::jsonb,45),
  ('wbs_area','6283','Sewage Treatment Plant',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "3"}'::jsonb,46),
  ('wbs_area','6284','Village',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "4"}'::jsonb,47),
  ('wbs_area','6285','Mining Open Pit',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "5"}'::jsonb,48),
  ('wbs_area','6286','Primary Crushing',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "6"}'::jsonb,49),
  ('wbs_area','6287','Tailings Storage Facility',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "7"}'::jsonb,50),
  ('wbs_area','6288','Rail Offloading Facility',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "8"}'::jsonb,51),
  ('wbs_area','6289','Explosive Magazine / Emulsion Facility',null,'{"l1": "6", "l2": "2", "l3": "8", "l4": "9"}'::jsonb,52),
  ('wbs_area','6290','Renewable Energy',null,'{"l1": "6", "l2": "2", "l3": "9", "l4": "0"}'::jsonb,53),
  ('wbs_area','6291','Administration and General Buildings',null,'{"l1": "6", "l2": "2", "l3": "9", "l4": "1"}'::jsonb,54),
  ('wbs_area','6292','11/33 kV Solar PV Substation 1 and Control Room 1',null,'{"l1": "6", "l2": "2", "l3": "9", "l4": "2"}'::jsonb,55),
  ('wbs_area','6293','Power Station 1 Photovoltaic Array, Inverters, and Transformers',null,'{"l1": "6", "l2": "2", "l3": "9", "l4": "3"}'::jsonb,56),
  ('wbs_area','7177','Off-Site Fan Sediments Bore Field 13',null,'{"l1": "7", "l2": "1", "l3": "7", "l4": "7"}'::jsonb,57),
  ('wbs_area','7177','Off-Site Fan Sediments Bore Field 41',null,'{"l1": "7", "l2": "1", "l3": "7", "l4": "7"}'::jsonb,58),
  ('wbs_area','7179','Off-Site Borehole Fieldwater Pipeline - Fan Sediments Construction Line',null,'{"l1": "7", "l2": "1", "l3": "7", "l4": "9"}'::jsonb,59),
  ('wbs_area','9120','Temporary Facilities',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "0"}'::jsonb,60),
  ('wbs_area','9121','Offices and Support Buildings',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "1"}'::jsonb,61),
  ('wbs_area','9122','Warehouse and Yards',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "2"}'::jsonb,62),
  ('wbs_area','9123','Shelters',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "3"}'::jsonb,63),
  ('wbs_area','9124','Power Generation',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "4"}'::jsonb,64),
  ('wbs_area','9125','Aggregate and Concrete',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "5"}'::jsonb,65),
  ('wbs_area','9126','Water System',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "6"}'::jsonb,66),
  ('wbs_area','9127','Fuel Stations',null,'{"l1": "9", "l2": "1", "l3": "2", "l4": "7"}'::jsonb,67),
  ('wbs_area','9130','Temporary Services',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "0"}'::jsonb,68),
  ('wbs_area','9131','Power',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "1"}'::jsonb,69),
  ('wbs_area','9132','Maintenance and Cleanup',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "2"}'::jsonb,70),
  ('wbs_area','9133','Personnel Transportation',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "3"}'::jsonb,71),
  ('wbs_area','9134','Survey, Inspection, and Quality Control',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "4"}'::jsonb,72),
  ('wbs_area','9135','Medical and Security',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "5"}'::jsonb,73),
  ('wbs_area','9136','Heating',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "6"}'::jsonb,74),
  ('wbs_area','9137','Fuel Supply',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "7"}'::jsonb,75),
  ('wbs_area','9138','Water, Sewage, and Waste Disposal',null,'{"l1": "9", "l2": "1", "l3": "3", "l4": "8"}'::jsonb,76),
  ('wbs_area','7337','Port Qasim PIBT Control Room',null,'{"l1": "7", "l2": "3", "l3": "3", "l4": "7"}'::jsonb,77)
on conflict (kind, code) do nothing;